# Generated by Django 4.1.4 on 2022-12-14 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_coursefeedback"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courses",
            options={
                "ordering": ("-created",),
                "verbose_name": "Courses",
                "verbose_name_plural": "Paid Courses",
            },
        ),
    ]
