# Generated by Django 4.1.4 on 2022-12-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_alter_courses_options"),
    ]

    operations = []
